export const mockStats = {
  unreadEmails: 5,
  pendingTasks: 12,
  activeProjects: 4,
  connectedApps: 2,
};

export const mockProjects = [
  {
    id: "1",
    name: "SentinelQA",
    description: "Clinical quality and performance analytics system for LCEMS",
    category: "EMS Leadership",
    status: "active" as const,
    tasksCount: 8,
    lastUpdated: "2026-04-09",
    color: "#6366f1",
  },
  {
    id: "2",
    name: "APEx360",
    description: "EMS evaluation and field training platform",
    category: "EMS Leadership",
    status: "active" as const,
    tasksCount: 5,
    lastUpdated: "2026-04-08",
    color: "#8b5cf6",
  },
  {
    id: "3",
    name: "Assemble",
    description: "Event and training management SaaS platform",
    category: "Wealth Building",
    status: "active" as const,
    tasksCount: 11,
    lastUpdated: "2026-04-07",
    color: "#06b6d4",
  },
  {
    id: "4",
    name: "ProficiencyAI",
    description: "AI-powered education and testing platform",
    category: "Wealth Building",
    status: "active" as const,
    tasksCount: 6,
    lastUpdated: "2026-04-06",
    color: "#10b981",
  },
];

export const mockTasks = [
  {
    id: "t1",
    title: "Design cardiac arrest QA dashboard",
    description: "Build the main analytics view for CARES data",
    project: "SentinelQA",
    priority: "high" as const,
    status: "todo" as const,
    dueDate: "2026-04-15",
  },
  {
    id: "t2",
    title: "Set up database schema",
    description: "PostgreSQL schema for case data",
    project: "SentinelQA",
    priority: "high" as const,
    status: "inprogress" as const,
    dueDate: "2026-04-12",
  },
  {
    id: "t3",
    title: "Build field evaluation form",
    description: "Mobile-friendly eval form for preceptors",
    project: "APEx360",
    priority: "medium" as const,
    status: "inprogress" as const,
    dueDate: "2026-04-14",
  },
  {
    id: "t4",
    title: "Draft Lt. orientation curriculum",
    description: "Content for May 14–27 orientation class",
    project: "APEx360",
    priority: "high" as const,
    status: "todo" as const,
    dueDate: "2026-04-20",
  },
  {
    id: "t5",
    title: "Stripe integration",
    description: "Payment processing for event registrations",
    project: "Assemble",
    priority: "high" as const,
    status: "review" as const,
    dueDate: "2026-04-11",
  },
  {
    id: "t6",
    title: "Landing page copy",
    description: "Write hero section and feature descriptions",
    project: "Assemble",
    priority: "medium" as const,
    status: "done" as const,
    dueDate: "2026-04-08",
  },
  {
    id: "t7",
    title: "AI question generation engine",
    description: "GPT-4 powered quiz generation from content",
    project: "ProficiencyAI",
    priority: "high" as const,
    status: "inprogress" as const,
    dueDate: "2026-04-18",
  },
  {
    id: "t8",
    title: "Follow up on Skyler Morgenson tuition issue",
    description: "Deputy Chief Johnson asked for follow-up with Skylar re: tuition reimbursement agreement",
    project: "SentinelQA",
    priority: "medium" as const,
    status: "todo" as const,
    dueDate: "2026-04-10",
  },
  {
    id: "t9",
    title: "Configure Railway deployment",
    description: "Deploy Albert OS to Railway for public access",
    project: "Assemble",
    priority: "medium" as const,
    status: "todo" as const,
    dueDate: "2026-04-11",
  },
  {
    id: "t10",
    title: "Pricing page design",
    description: "Three-tier pricing for ProficiencyAI",
    project: "ProficiencyAI",
    priority: "low" as const,
    status: "done" as const,
    dueDate: "2026-04-07",
  },
];

export const mockApps = [
  {
    id: "gmail",
    name: "Gmail",
    description: "Email monitoring and management",
    connected: true,
    lastSync: "2 min ago",
    icon: "📧",
    color: "#EA4335",
  },
  {
    id: "monday",
    name: "Monday.com",
    description: "Project and board management",
    connected: true,
    lastSync: "15 min ago",
    icon: "📋",
    color: "#FF3D57",
  },
  {
    id: "youtube",
    name: "YouTube",
    description: "Video publishing and analytics",
    connected: false,
    lastSync: null,
    icon: "🎥",
    color: "#FF0000",
  },
  {
    id: "instagram",
    name: "Instagram",
    description: "Social media posting",
    connected: false,
    lastSync: null,
    icon: "📸",
    color: "#E1306C",
  },
  {
    id: "twitter",
    name: "Twitter / X",
    description: "Social media and announcements",
    connected: false,
    lastSync: null,
    icon: "🐦",
    color: "#1DA1F2",
  },
  {
    id: "github",
    name: "GitHub",
    description: "Code repository management",
    connected: false,
    lastSync: null,
    icon: "🐙",
    color: "#333",
  },
  {
    id: "notion",
    name: "Notion",
    description: "Notes and documentation",
    connected: false,
    lastSync: null,
    icon: "📝",
    color: "#000",
  },
  {
    id: "calendar",
    name: "Google Calendar",
    description: "Schedule and event management",
    connected: false,
    lastSync: null,
    icon: "📅",
    color: "#4285F4",
  },
];

export const mockLogs = [
  {
    id: "l1",
    timestamp: "2026-04-09 14:12",
    action: "Built AUTONOMY.md permission framework",
    outcome: "success" as const,
    notes: "Created green/yellow/red action tiers",
  },
  {
    id: "l2",
    timestamp: "2026-04-09 13:34",
    action: "Read and summarized Gmail inbox (5 messages)",
    outcome: "success" as const,
    notes: "Flagged Skyler Morgenson follow-up as action item",
  },
  {
    id: "l3",
    timestamp: "2026-04-09 13:30",
    action: "Wired Gmail MCP to OpenClaw gateway config",
    outcome: "success" as const,
    notes: "Registered @shinzolabs/gmail-mcp as MCP server",
  },
  {
    id: "l4",
    timestamp: "2026-04-09 11:25",
    action: "Installed Canvas skill from OpenClaw bundle",
    outcome: "success" as const,
    notes: "Copied to workspace/skills/canvas/",
  },
  {
    id: "l5",
    timestamp: "2026-04-09 11:10",
    action: "Diagnosed gateway bind issue for mobile pairing",
    outcome: "warning" as const,
    notes: "Gateway bound to loopback — needs LAN or Tailscale",
  },
  {
    id: "l6",
    timestamp: "2026-04-09 10:45",
    action: "Updated MEMORY.md with Gmail and Monday integrations",
    outcome: "success" as const,
    notes: "Memory sync after session context established",
  },
  {
    id: "l7",
    timestamp: "2026-04-09 10:30",
    action: "Heartbeat check — email scan",
    outcome: "success" as const,
    notes: "No urgent items found",
  },
  {
    id: "l8",
    timestamp: "2026-04-09 09:15",
    action: "Scaffolded Albert OS Next.js project",
    outcome: "success" as const,
    notes: "create-next-app with TypeScript + Tailwind",
  },
  {
    id: "l9",
    timestamp: "2026-04-09 09:00",
    action: "Attempted Codex build — bubblewrap missing",
    outcome: "error" as const,
    notes: "Switched to direct build approach",
  },
  {
    id: "l10",
    timestamp: "2026-04-09 08:50",
    action: "Installed Codex CLI via npm",
    outcome: "success" as const,
    notes: "codex-cli 0.118.0",
  },
];

export const mockActivity = [
  { id: "a1", text: "Gmail inbox checked — 5 unread messages", time: "2 min ago", icon: "📧" },
  { id: "a2", text: "Albert OS build started", time: "25 min ago", icon: "🔨" },
  { id: "a3", text: "AUTONOMY.md framework created", time: "1 hr ago", icon: "🤖" },
  { id: "a4", text: "Gmail MCP connected successfully", time: "2 hr ago", icon: "✅" },
  { id: "a5", text: "Canvas skill installed", time: "3 hr ago", icon: "🎨" },
];
