'use client';
import { useState } from 'react';
import TopBar from '@/components/TopBar';
import useIsMobile from '@/components/useIsMobile';

const exampleCode = `// Generated by Albert
import React, { useState } from 'react';

export default function Component() {
  const [count, setCount] = useState(0);
  
  return (
    <div className="p-8 text-center">
      <h1 className="text-2xl font-bold mb-4">
        Counter: {count}
      </h1>
      <button
        onClick={() => setCount(c => c + 1)}
        className="bg-indigo-500 text-white px-6 py-2 rounded-lg"
      >
        Click me
      </button>
    </div>
  );
}`;

export default function VibePage() {
  const isMobile = useIsMobile();
  const [prompt, setPrompt] = useState('');
  const [code, setCode] = useState(exampleCode);
  const [loading, setLoading] = useState(false);

  const generate = async () => {
    if (!prompt.trim()) return;
    setLoading(true);
    try {
      const res = await fetch('/api/vibe', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ prompt }) });
      const data = await res.json();
      setCode(data.code || '// Generation complete');
    } catch {
      setCode('// Error generating code. Please try again.');
    }
    setLoading(false);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
      <TopBar title="Vibe Coder" />
      <div style={{ flex: 1, display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: 0, overflow: isMobile ? 'visible' : 'hidden' }}>
        {/* Left: Prompt */}
        <div style={{ borderRight: isMobile ? 'none' : '1px solid var(--border)', borderBottom: isMobile ? '1px solid var(--border)' : 'none', display: 'flex', flexDirection: 'column', padding: isMobile ? 14 : 24, gap: 16 }}>
          <div>
            <h2 style={{ margin: '0 0 8px', fontSize: 15, fontWeight: 600, color: '#fff' }}>Describe what you want to build</h2>
            <p style={{ margin: 0, fontSize: 13, color: 'var(--text-muted)' }}>Plain English. Albert will generate the code.</p>
          </div>
          <textarea
            value={prompt}
            onChange={e => setPrompt(e.target.value)}
            placeholder="e.g. Build a dashboard card that shows today's cardiac arrest stats with a trend chart..."
            style={{ flex: 1, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8, padding: 14, color: 'var(--text)', fontSize: 14, resize: 'none', outline: 'none', lineHeight: 1.5, minHeight: 200 }}
          />
          <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
            <button onClick={generate} disabled={loading || !prompt.trim()} style={{ flex: 1, background: 'var(--primary)', border: 'none', borderRadius: 7, padding: '10px 16px', color: '#fff', fontSize: 14, fontWeight: 500, cursor: 'pointer', opacity: (!prompt.trim() || loading) ? 0.5 : 1 }}>
              {loading ? '⚙️ Generating...' : '✨ Generate'}
            </button>
            <button style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 7, padding: '10px 16px', color: 'var(--text-muted)', fontSize: 14, cursor: 'pointer' }}>
              🚀 Deploy
            </button>
          </div>

          {/* Example prompts */}
          <div>
            <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 8 }}>Try these:</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {[
                'Build a QA metrics dashboard for EMS',
                'Create a training schedule calendar',
                'Make a YouTube content calendar tracker',
              ].map(ex => (
                <button key={ex} onClick={() => setPrompt(ex)} style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 6, padding: '7px 10px', color: 'var(--text-muted)', fontSize: 12, cursor: 'pointer', textAlign: 'left' }}>
                  {ex}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Right: Code output */}
        <div style={{ display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
          <div style={{ padding: '12px 20px', borderBottom: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontSize: 13, color: 'var(--text-muted)' }}>Generated Code</span>
            <button onClick={() => navigator.clipboard.writeText(code)} style={{ background: 'transparent', border: '1px solid var(--border)', borderRadius: 5, padding: '4px 10px', color: 'var(--text-muted)', fontSize: 12, cursor: 'pointer' }}>Copy</button>
          </div>
          <pre style={{ flex: 1, margin: 0, padding: isMobile ? 14 : 20, overflow: 'auto', fontSize: 13, lineHeight: 1.6, color: '#a5b4fc', fontFamily: 'monospace', background: '#0a0a0a', whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>
            <code>{code}</code>
          </pre>
        </div>
      </div>
    </div>
  );
}
